FROM maven:3.8.3-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn clean package

FROM openjdk:11-jre-slim

WORKDIR /app

# Copy the JAR file built in the first stage
COPY --from=build /app/target/rabbitmq-integration.jar /app/app.jar

EXPOSE 3306 5672

CMD ["java", "-jar", "app.jar"]
